
dist: trusty
sudo: required
 
language: node_js
node_js:
  - "10.13.0"
  
addons:
  chrome: stable
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_script:
    - "sudo chown root /opt/google/chrome/chrome-sandbox"
    - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
cache:
  directories:
     - ./node_modules
 
install:
  - npm install
 
script:
  - npm run test -- --single-run --no-progress --browser=ChromeHeadlessCI